name: CI/CD

on:
  push:
    branches: [main]

env:
  REGION: europe-west1
  SERVICE: my-node-express-app

jobs:
  build-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Build TypeScript
        run: npm run build

      - name: Build Docker image
        run: docker build -t europe-west1-docker.pkg.dev/${{ env.GCP_PROJECT }}/${{ env.SERVICE }}/${{ env.SERVICE }}:${{ github.sha }} .

      - name: Authenticate to Google Cloud
        uses: google-github-actions/auth@v2
        with:
          credentials_json: ${{ env.GCP_SA_KEY }}

      - name: Configure Docker for Artifact Registry
        run: gcloud auth configure-docker europe-west1-docker.pkg.dev

      - name: Push Docker image
        run: docker push europe-west1-docker.pkg.dev/${{ env.GCP_PROJECT }}/${{ env.SERVICE }}/${{ env.SERVICE }}:${{ github.sha }}

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          image: europe-west1-docker.pkg.dev/${{ env.GCP_PROJECT }}/${{ env.SERVICE }}/${{ env.SERVICE }}:${{ github.sha }}
          region: ${{ env.REGION }}